version: "{build}"

image: Visual Studio 2017

before_build:
  - git submodule init
  - git submodule update
  - nuget restore IIS.Compression\Compression.sln

build_script:
  - msbuild IIS.Compression\Compression.sln /p:platform=x86 /p:configuration=Release
  - msbuild IIS.Compression\Compression.sln /p:platform=x64 /p:configuration=Release